### PR TITLE
Fix for md5 chaos in the gem for 1.8 and 1.9.

### PR DESCRIPTION
**Pull request by ghost**
Applied a fix for this gem to make it run without problems in both Ruby 1.8.7/1.9.2+. Tries to load the library from 1.8.7, and if it does not find it, captures the exception (rescue) and loads the library from 1.9.2.

### CODE REVIEW

**Comment by drbrain** [comment]
I think Digest::MD5 can be used everywhere for 1.8.7+:

``` ruby
require 'digest'

Digest::MD5.new << packet
```

Would you mind updating the pull request?

**Comment by ghost** [comment]
Oh, that's true!

I got confused. Will do, thanks!

**Comment by ghost** [comment]
Ok, fixed my mistake, sorry!

**Comment by drbrain** [comment]
Hrm, there seem to be no changes now.  Where you having a problem, or should I close this pull request?

**Comment by ghost** [comment]
No, I don't have problems. I already closed it. (Couldn't reproduce it again, even having a different gemset for that gem!)

**Pull request closed without merging**
